name: "User Story"
description: "Template for creating a user story"
title: "[User Story] "
labels: ["user-story"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **As a** [role]  
        **I need** [function]  
        **So that** [benefit]  

  - type: textarea
    id: details_and_assumptions
    attributes:
      label: "Details and Assumptions"
      description: "Document what you know"
      placeholder: "* [document what you know]"

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria (Gherkin format)"
      description: |
        Use Gherkin syntax:
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
      placeholder: |
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
