name: "User Story"
description: "Template for user stories with Gherkin acceptance criteria"
title: "[User Story] "
labels:
  - user story
  - needs grooming
assignees: []

body:
  - type: input
    id: role
    attributes:
      label: "As a"
      description: "Describe the role of the user"
      placeholder: "e.g. Admin, Customer, System"
    validations:
      required: false

  - type: input
    id: need
    attributes:
      label: "I need"
      description: "Describe what is needed"
      placeholder: "e.g. reset my password"
    validations:
      required: false

  - type: input
    id: benefit
    attributes:
      label: "So that"
      description: "Describe the benefit or value"
      placeholder: "e.g. reduce support calls"
    validations:
      required: false

  - type: textarea
    id: details_and_assumptions
    attributes:
      label: "Details and Assumptions"
      description: "Document what you know, assumptions, dependencies"
      placeholder: |
        * [document what you know]
        * [assumptions]
        * [dependencies]

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria (Gherkin format)"
      description: |
        Use Gherkin syntax:
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
      placeholder: |
        ```gherkin
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
        ```
