name: "User Story"
description: "Template for user stories with Gherkin acceptance criteria"
title: "[User Story] "
labels:
  - user story
  - needs grooming
assignees: []

body:
  - type: input
    id: role
    attributes:
      label: "As a"
      description: "Role of the user"
      placeholder: "[role]"
    validations:
      required: false

  - type: input
    id: need
    attributes:
      label: "I need"
      description: "Function or capability required"
      placeholder: "[function]"
    validations:
      required: false

  - type: input
    id: benefit
    attributes:
      label: "So that"
      description: "Expected benefit"
      placeholder: "[benefit]"
    validations:
      required: false

  - type: textarea
    id: details_and_assumptions
    attributes:
      label: "Details and Assumptions"
      description: "Document what you know"
      placeholder: |
        * [document what you know]
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria (Gherkin)"
      description: |
        Write in Gherkin format:
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
      placeholder: |
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
    validations:
      required: false
